name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm start & sleep 5 && npm test
      - name: Upload tests report(cypress mochaawesome merged HTML report)
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: reports
